### ISSUE TITLE
Fails to start on first run

### ISSUE THREAD

**Issue by DragRedSim** [laromicas/datoso#2]
Just installed in a venv and attempted to run as per the readme. Recieved the following:
`(.venv) PS D:\David\Desktop\roms management\02RomVault - FullSets Network> datoso --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\David\Desktop\roms management\02RomVault - FullSets Network\.venv\Scripts\datoso.exe\__main__.py", line 7, in <module>
  File "D:\David\Desktop\roms management\02RomVault - FullSets Network\.venv\Lib\site-packages\datoso\__main__.py", line 455, in main
    detect_first_run()
  File "D:\David\Desktop\roms management\02RomVault - FullSets Network\.venv\Lib\site-packages\datoso\database\seeds\dat_rules.py", line 69, in detect_first_run
    if not len(System.all()):
               ^^^^^^^^^^^^
  File "D:\David\Desktop\roms management\02RomVault - FullSets Network\.venv\Lib\site-packages\datoso\database\models\datfile.py", line 100, in all
    System._DB.DB = DB  # pylint: disable=invalid-name
    ^^^^^^^^^^^^^
AttributeError: 'ModelPrivateAttr' object has no attribute 'DB'`

**Comment by laromicas** [comment]
Released v0.3.8 that fixed pydantic version to v1 as v2 seems to be incompatible. Trying to remove pydantic dependency on next version.

**Comment by laromicas** [comment]
Try to clear venv prior to install new version.
